### ISSUE TITLE
[ENHANCEMENT] UI Custumization.

### ISSUE THREAD

**Issue by wqq-z** [Skwrr/Dexterion#13]
Literaly a tab to custumize ImGui.

**Comment by wqq-z** [comment]
@Skwrr discord req sent.

**Comment by Skwrr** [comment]
I got no friend request

**Comment by wqq-z** [comment]
ok can u resend me ur username?

**Comment by wqq-z** [comment]
sent again @Skwrr is kvfs_?

**Comment by Skwrr** [comment]
> sent again @Skwrr is kvfs_?

yes, received friend request

**Comment by Skwrr** [comment]
> Literaly a tab to custumize ImGui.

Something like AimStar do?

**Comment by wqq-z** [comment]
i search and i found smt like this https://www.youtube.com/watch?v=iOQ7ZrNQLuI
