### ISSUE TITLE
order json loading into Dexterion

### ISSUE THREAD

**Issue by LauraSavall** [Skwrr/Dexterion#14]
The weird thing is the following

New update of CS2, I dumped .json, runned Dexterion with new .json, freshly dumped, no problem, even if updateoffset.cmd execute at launch (on my side), but "update" occured...
then, I relaunched it, and know it crash... as if .json were loaded BEFORE the cmd popup and the run of "updateoffset.cmd" occurs

I don't know when .json are loaded, but looks like it's BEFORE L.58 if you can enlight me

**Comment by wqq-z** [comment]
So, ur problem is that the upset update its ipdate automatically ehen you open dexterion?

**Comment by LauraSavall** [comment]
@wqq-z 
I made a PR to auto update offsets.json, buttons.json & client.dll.json
https://github.com/Skwrr/Dexterion/commit/b4c5ab0d18749e32c730bf6cc72c405d3a31551f

BUT it looks like even if it works, JSON are loaded in Dexterion BEFORE the update in code occurs. 
So even if I do the autoupdate, and it works, Dexterion crash as it loads old .json

**Comment by wqq-z** [comment]
Im clonning ur branch and ill try to fix it. @LauraSavall @kristofhracza

**Comment by LauraSavall** [comment]
> Im clonning ur branch and ill try to fix it. @LauraSavall @kristofhracza 

Okay, thanks, but you will see, change updateoffset.cmd to have "rm client.dll.json" for example... Run Dexterio, it will load up, rm the file but Dexterio work fine....

So idk where JSON are loaded before it open and show us "waiting for CS2" etc

**Comment by wqq-z** [comment]
So i see dexterion is not downloading the offsets or is downloading the offsets in the incorrect path

**Comment by LauraSavall** [comment]
> So i see dexterion is not downloading the offsets or is downloading the offsets in the incorrect path

Dexterion download it in the right path. That's not the problem

**Comment by LauraSavall** [comment]
Corrupt your .JSON by deleting one number on it, any one

If you run the "standard" version, it will boot then crash as .JSON is not compatible with CS2 version ....

If you do the same with my version, it will replace .JSON, boot and crash because JSON are loaded BEFORE the download of them....because if you check the .JSON, it will be the good one

**Comment by LauraSavall** [comment]
As Dexterio refuse to boot if a .JSON is missing.... But IDK where .JSON are loaded, not in dexterio.cpp or I'm missing something

**Comment by LauraSavall** [comment]
I see them here.... But IDK where this is used
https://github.com/Skwrr/Dexterion/blob/master/json%2FjsonOps.hpp

**Comment by wqq-z** [comment]
i dont see that engine2.dll.json is used in Dexterion

**Comment by wqq-z** [comment]
My brain is fucked.

**Comment by LauraSavall** [comment]
> My brain is fucked. 

Mine too.... Waiting for information from @Skwrr or @kristofhracza in order to make autoupdate at the right place in code

**Comment by Skwrr** [comment]
I'll find where the JSON is loaded because I dont remember where it load for the first time

**Comment by wqq-z** [comment]
When i run dexterion the app is not crashing but code anything is not working for some reason.

**Comment by wqq-z** [comment]
My debugger is broken

**Comment by LauraSavall** [comment]
> I now know where the issue is.
> 
> You could've fixed it by youself by running a debugger in VS. It literally tell you where it tries to load the dll.
> 
> attributes.hpp - 24
> 
> I'll do a quick fix rn into master
> 

I didn't think about debugger, not used to VS my bad
