### ISSUE TITLE
the cheat does not render and the console quits 

### ISSUE THREAD

**Issue by VC1W** [Skwrr/Dexterion#16]
**Describe the bug**
after printing rendering ui it closes the console window, which makes the cheat not render/working

**To Reproduce**
try running the cheat

**Expected behavior**
the cheat should render 

**Screenshots**

**Desktop (please complete the following information):**
 - Version 23

**Additional context**
Add any other context/information about the problem here.

**Configuration file**
For easier reproduction, please attach your configuration file here (ONLY PASTEBIN, HASTEBIN, PRIVATEBIN, ETC)

**Comment by LauraSavall** [comment]
You didn't run updateoffset.cmd ...

**Comment by VC1W** [comment]
ofc i did u take me for a retard=?

**Comment by LauraSavall** [comment]
We never know... A lot of people don't read 

So the problem is maybe offset downloaded from a2x csdumper aren't updated 

So you are running oldest .JSON, which doesn't work for now
(I guess, not at home RN)

**Comment by wqq-z** [comment]
We are working on it.

**Comment by VC1W** [comment]
ye well he seemed to had fixed it 13 mins ago, it happend bc of a typo he made ig

**Comment by wqq-z** [comment]
Issue was found Realese 23 is broken.
Reason: Misspelling, Please Use The Lastest Realese.

**Comment by VC1W** [comment]
mhm thanks btw can someone tell me why bhop dont work
