### ISSUE TITLE
bunnyhop does not work 

### ISSUE THREAD

**Issue by VC1W** [Skwrr/Dexterion#17]
**Describe the bug**
so when focused in the game/when the game is in focus, while holding space it jumps 1 time, but when the game is not in focus for example when clicking in dexterion or another window bhop is working fine if i hold down space bar 

**To Reproduce**
1. Go to 'misc'
2. Enable 'bhop'
3. Do 'hold down space while game is in focus and bhop wont work, if u try to hold down space while game is not in focus bhop is bhopping'

**Expected behavior**
it should bhop when space is held down if the game is in focus

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Add any other context/information about the problem here.

**Configuration file**
For easier reproduction, please attach your configuration file here (ONLY PASTEBIN, HASTEBIN, PRIVATEBIN, ETC)

**Comment by wqq-z** [comment]
BunnyHop feature as external cheaat it will work weird. But you can rate frame to 32 using following command. `fps_max 32` in cs2 console but as i said it works weird.

**Comment by Skwrr** [comment]
As wqq-z said, BHop works weird in external cheats. The only way to fix your issue is to make an internal cheat.
