### ISSUE TITLE
[ISSUE/BUG] BombTimer enable = crash

### ISSUE THREAD

**Issue by LauraSavall** [Skwrr/Dexterion#18]
If Bombtimer is ON, Dexterion will crash...

**Comment by wqq-z** [comment]
Im not having this issue can u expecific your version?

**Comment by wqq-z** [comment]
Definetly Bomb timer is working and anything is crashing.

**Comment by LauraSavall** [comment]
Hm ok I'll dig into it then

**Comment by Skwrr** [comment]
Did you solve this?

**Comment by LauraSavall** [comment]
Yup, it's just MY repo who is fucked up when I updated with your commits
