### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by V1ERA** [Skwrr/Dexterion#19]
Make a driver and read game memory with it
Make the GUI better make it look more beautiful
Add Auto Updater so after launching it it gets the latest offsets from A2X's cs2 dumper
add ESP distance
add toggle for everything like neverlose
remove ANY write memory features even bhop or atleast add a confirmation for it
improve performance

**Comment by LauraSavall** [comment]
Add Auto Updater won't be added as UC doesn't want internet connexion :
https://github.com/Skwrr/Dexterion/pull/9#issuecomment-2225941602

**Comment by LauraSavall** [comment]
@V1ERA 
> remove ANY write memory features even bhop or atleast add a confirmation for it

Created a PR about it : https://github.com/Skwrr/Dexterion/pull/22

**Comment by wqq-z** [comment]
Closing this, the following freatures are be working on, New GUI And Custumization, WriteMem Alert, Improve Performance. Others freatures please re-open a new request giving a full deail of the freature wanted.
