### ISSUE TITLE
Bomb timer feature ?

### ISSUE THREAD

**Issue by LauraSavall** [Skwrr/Dexterion#2]
Hi, first of all, awesome work !
Do you think it's possible to add this kind of Script ;
https://github.com/RatPoison-dev/RatPoison/blob/master/src/main/kotlin/rat/poison/scripts/BombTimer.kt
😁
In order to know if someone is defusing, if he has time to defuse etc....?

**Comment by Skwrr** [comment]
Could be possible.
RatPoison is made in Kotlin and has a different structure than I do, I might have to do it all by myself or request some help in UnknownCheats.

**Comment by Skwrr** [comment]
Don't worry, I'll find a way to import it into my code as I did with the spectator list.

**Comment by LauraSavall** [comment]
Oh nice, so you did translate the .kt into yours ? Awesome !

I will look into it anyways 🤣 in order to understand how the translation between his code and yours is working 
I'm too curious

**Comment by LauraSavall** [comment]
Found this if it can help :
https://github.com/CowNowK/AimStar/blob/09d1b2b0560b290993a1a9a9c6b5ba590c64b2e2/CS2_External/Features/BombTimer.h#L4

**Comment by Skwrr** [comment]
> Found this if it can help : https://github.com/CowNowK/AimStar/blob/09d1b2b0560b290993a1a9a9c6b5ba590c64b2e2/CS2_External/Features/BombTimer.h#L4

This really helped more than the other kotlin file.
Thanks to this code I could make draggable GUIs lol.

Bomb Timer added in V8
