### ISSUE TITLE
[ENHANCEMENT] Add 2560 x1440 compatibility

### ISSUE THREAD

**Issue by LauraSavall** [Skwrr/Dexterion#20]
By default, overlay is for 1920 x 1080 but some people play with a 2560 x1440

Is there a way to make this code dynamic in order to auto scale the screen size ?

https://github.com/Skwrr/Dexterion/blob/ea89b450040f644af73ea7b564d9f5b376a9f916/gui/overlay.cpp#L28

**Comment by Skwrr** [comment]
Fixed on Release 30
