### ISSUE TITLE
[ENHANCEMENT] Config Tab

### ISSUE THREAD

**Issue by suspectedesp** [Skwrr/Dexterion#24]
**Is your feature request related to a problem? Please describe.**
no, just an enhancement idea

**Describe the solution you'd like**
The window for the config tab is so big, how about adding more stuff to it? e.g. loading multiple configs with an individual name

**Comment by Skwrr** [comment]
It's already in the TODO list. We will be adding this soon.

**Comment by suspectedesp** [comment]
@Skwrr I decided to make it myself, look at the [pull request](https://github.com/Skwrr/Dexterion/pull/35) here, you can remove it from the to-do list :)

**Comment by Skwrr** [comment]
I merged your PR, but won't close this and mark it as done because I will be working with it. You can check the review on your PR (#35)

**Comment by Skwrr** [comment]
Fixed on v2.2.0
