### ISSUE TITLE
[Issue/Bug]

### ISSUE THREAD

**Issue by Skwrr** [Skwrr/Dexterion#27]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Dexterion version: 32
- Describe install method of offsets: .cmd file
```

### 📝 Description

1. Nothing happens
2. this is cool
3. Great work!

### ⚙️ Configuration Files

Isn't there an upload file feature or smth?
Would be good

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/e55dbe06-0def-488a-a510-0ae10b2522ad)

**Comment by Skwrr** [comment]
I think the workflow doesnt work

**Comment by wqq-z** [comment]
im on it
