### ISSUE TITLE
[Bug] C4 Showing when is out of tab

### ISSUE THREAD

**Issue by wqq-z** [Skwrr/Dexterion#43]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Dexterion version: Dev-Branch
- Describe install method of offsets: -
```

### 📝 Description

C4 is showing when you're not showing in the game / you're out of tab.

What should happends: hide overlay ( ESP) the c4 when you;'re not in the game.

**Comment by wqq-z** [comment]
This a known bug ill fix it

**Comment by wqq-z** [comment]
![Screenshot 2024-07-17 114520](https://github.com/user-attachments/assets/6ebe94d7-47d8-4d2e-8de7-b8a4ee15164e)
![Screenshot 2024-07-17 114529](https://github.com/user-attachments/assets/ccec9faa-82ec-43a3-b574-90ed937c99d9)

**Comment by wqq-z** [comment]
Fixing the bug

**Comment by suspectedesp** [comment]
add
```cpp
			if (!overlayESP::isMenuOpen()) {
				if (!misc::isGameWindowActive()) return;
			}
```
at line 106 in entry.cpp and voilà!

**Comment by suspectedesp** [comment]
https://github.com/Skwrr/Dexterion/pull/47 pull for reference
