### ISSUE TITLE
[Enhancement]Add back update offsets

### ISSUE THREAD

**Issue by Blqtent** [Skwrr/Dexterion#50]
### 📝 Provide a description of the new feature

idfk why u guys removed it

### ➕ Additional Information

Plez

**Comment by LauraSavall** [comment]
This [commit](https://github.com/Skwrr/Dexterion/commit/1e90da9399674c0a213dcfb6d761d22f9663b5b2) deleted updateoffset.cmd

But README and program ask to run it... :
https://github.com/Skwrr/Dexterion/blob/c5446d4cba8de96d1b4868888d8f337785bb593d/README.md?plain=1#L30

@Blqtent [clic here to show updateoffset.cmd](https://github.com/Skwrr/Dexterion/blob/dc92dded61e22553d044e95fccbc87d7e15f295d/updateoffset.cmd)

**Comment by LauraSavall** [comment]
@wqq-z

**Comment by wqq-z** [comment]
Uh

**Comment by wqq-z** [comment]
wrong deleted fixed rn
