### ISSUE TITLE
[QUESTION] Work on FaceIT ?

### ISSUE THREAD

**Issue by LauraSavall** [Skwrr/Dexterion#53]
### 📝 Provide a description of the new feature

Juste a small question about Dexterion and FaceIT...was wondering if it's detected on FaceIT...

**Comment by Skwrr** [comment]
I think it is. but you're free to test it for yourself!

**Comment by suspectedesp** [comment]
better to re-code it to use a kernelmode driver before testing it out though

**Comment by wqq-z** [comment]
Nope, i think you will get an insta ban or 1d delayed ban cuz Face IT is a kernel anti-cheat you should re-code or make it invisible to face-it

**Comment by wqq-z** [comment]
Closing issue, conclusión all cheats works in faceit but as face.it is kernel anti-cheat your acc will be banned in 1 or 2 days. You should create a private cheat bypassing faceit anti-cheat that would benmore secured.
