### ISSUE TITLE
- add Tkazer back to exloader!

### ISSUE THREAD

**Issue by StevenTheProLearner** [Skwrr/Dexterion#57]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- add Tkazer back to exloader!
```

### 📝 Description

- add Tkazer back to exloader!

### ⚙️ Configuration Files

- add Tkazer back to exloader!

### 📸 Screenshots

- add Tkazer back to exloader!

**Comment by misaelxd2** [comment]
we need te old version

**Comment by wqq-z** [comment]
What happends? Specific this please

**Comment by wqq-z** [comment]
Bruh, this repo is for dexterion use only dont open issued about non dedterion issues.
