### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by MRspekacek** [Skwrr/Dexterion#58]
### 📝 Provide a description of the new feature

make a version where u dont need to have opened cs2 bcs iam not playing from my account iam using GeForce Now and i cannot enable any hack with it so iam hopping on you. Thnaks

### ➕ Additional Information

uhh the cheat must be started at desktop to work then. Thanks

**Comment by wqq-z** [comment]
This imposible because nvidia run cs2 in their server and we cannot acess nvidia server i think. To dl that we need tl do s step to read cs2 memory from nvidia servers. And this difficult

**Comment by Svxy** [comment]
Yeah that isn’t possible.
