### ISSUE TITLE
visibility check on aimbot tab makes the aimbot not work ever, even when they are visible

### ISSUE THREAD

**Issue by VC1W** [Skwrr/Dexterion#6]

**Comment by VC1W** [comment]
ye the visibilty check does not work on esp and aimbot tab

**Comment by Skwrr** [comment]
This is not an issue at all.

The method Dexterion uses to check if a player is visible is bSpottedByMask.
This is very slow and does not work properly sometimes.

I might change it and add it in the TODO list.

**Comment by Skwrr** [comment]
Visibility check on ESP works a little different, it only change the bounding box fill color when you can see the enemy.
